from enum import Enum

class Team(Enum):
    RED = 0
    BLUE = 1

class Color(Enum):
    __order__ = 'RED BLUE NEUTRAL ASSASSIN'
    RED = Team.RED.value
    BLUE = Team.BLUE.value
    NEUTRAL = 2
    ASSASSIN = 3

class Role(Enum):
    SPYMASTER = 0
    OPERATIVE = 1

class Reward(Enum):
    IDLE = 0
    HINT_UNPARSEABLE = -10
    HINT_MULTIPLE = -5
    HINT_PARSEABLE = 1
    HINT_INVALID_COUNT = -3
    HINT_VALID_COUNT = 1
    HINT_WORD_ON_BOARD = -3
    HINT_VALID_WORD = 1
    GUESS_UNPARSEABLE = -10
    GUESS_SKIP = -1
    GUESS_MULTIPLE = -5
    GUESS_PARSEABLE = 1
    GUESS_NOT_ON_BOARD = -3
    GUESS_ALREADY_MADE = -3
    GUESS_VALID = 1


    CORRECT_GUESS_OPERATIVE = 1
    CORRECT_GUESS_SPYMASTER = 1
    ALL_GUESSES_BONUS_OPERATIVE = 1
    ALL_GUESSES_BONUS_SPYMASTER = 1
    NEUTRAL_GUESS_OPERATIVE = -1
    NEUTRAL_GUESS_SPYMASTER = -1
    WRONG_GUESS_OPERATIVE = -3
    WRONG_GUESS_SPYMASTER = -3
    ASSASSIN_GUESS_OPERATIVE = -10
    ASSASSIN_GUESS_SPYMASTER = -10
    WIN = 10
    LOSS = -10